<?xml version="1.0"?>
<package format="3">
  <name>ins_driver_ez21</name>
  <version>0.1.0</version>
  <description>ROS 2 INS driver that reads CAN frames and publishes odometry for EZ21-class devices.</description>

  <maintainer email="nvidia@example.com">nvidia</maintainer>
  <license>Apache License 2.0</license>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>autoware_adapi_v1_msgs</depend>
  <depend>autoware_internal_planning_msgs</depend>
  <depend>autoware_perception_msgs</depend>
  <depend>autoware_planning_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
