<?xml version="1.0"?>
<package format="3">
  <name>scout_sensor_kit_description</name><version>0.1.0</version>
  <description>ELE Scout model and Autoware integration.</description>
  <maintainer email="maintainers@unmanned-systems-lab.invalid">Unmanned Systems Lab</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  
  <export><build_type>ament_cmake</build_type></export>
</package>
